# Generated by Django 3.1 on 2021-02-21 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goalname', models.CharField(blank=True, max_length=300)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('time', models.IntegerField(blank=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
