# Generated by Django 3.1 on 2021-02-20 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=300)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('budgetCategory', models.CharField(default='None', max_length=300, null=True)),
                ('isShared', models.BooleanField(default=False)),
                ('sharedWith', models.CharField(blank=True, max_length=300, null=True)),
                ('date', models.DateField()),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
