# Generated by Django 3.1.7 on 2021-02-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0004_auto_20210221_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingpay',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
