# Generated by Django 3.1.7 on 2021-02-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0005_auto_20210221_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingpay',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
